---
title: "Assignment 1"
author: "Ghazal"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Clearing the environment
rm(list=ls())

# Loading the Libraries
library(tidyverse)
library(modelsummary)
library(fixest)
library(kableExtra)
library(data.table)
library(ggplot2)
library(GGally)
library(viridis)
library(caret)
library(grid)
library(dplyr)
library(gridExtra)
library(grid)
library(viridis)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Importing the data
data_org <- read_csv("https://osf.io/4ay9x/download")


# Filtering the data for the chosen occupation
dt <- data_org %>% filter(occ2012==630)
dt <-  data.table(dt)

```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Counting the number of observations in each occupation
#aggregate((count = data_org$occ2012), list(value = data_org$occ2012), length)


```


```{r message=FALSE, warning=FALSE, include=FALSE}



# Creating new variable for earnings per hour and log of it
dt <- dt %>% 
  
  # Create : Female dummy variable
  mutate(female=as.numeric(sex==2)) %>% 
  
  # Create : hourly wage (earning per number of hours worked per week)
  mutate(w = earnwke/uhours) %>%
  
  # Add : log of wage
  mutate(lnw=log(w)) %>% 
  
  # Filter : Education is Bachelor's degree or higher
  filter(grade92 >= 38) %>% 
  
  # Filter : Age is above 20 years old
  filter(age>=18) %>% 
  
  # Filter : wage more than USD 1
  filter(w>1) %>% 
  
  # Create : Education Dummies
  mutate(
  no_degree=as.numeric(grade92<=40),
  ed_associate=as.numeric(grade92==41 |grade92==42) ,
  ed_BA=as.numeric(grade92==43),
  ed_MA=as.numeric(grade92==44),
  ed_Profess = as.numeric(grade92==45),
  ed_PhD = as.numeric(grade92==46))

dt <- dt[grade92 <= 40, educ := "No Degree"][grade92==41 | grade92==42, educ := "Associate" ][grade92 == 43, educ := "Bachelors"][grade92 == 44, educ := "Masters"][grade92 == 45, educ := "Professional"][grade92 == 46, educ := "PhD"]

# Looking for education data summary
datasummary(w * as.factor(educ) ~ N + Percent() + mean, data = dt)



# Looking for calss data summary
datasummary(w*as.factor(class) ~ N + Percent() + mean, data = dt)  


    # Create age squared
dt <-  dt %>% mutate(agesq=age^2) %>% 
  
  # Create Private Sector Dummy
  mutate(privt_sec = as.numeric(class=="Private, Nonprofit" | class== "Private, For Profit"))



# Looking for male and female data summary
datasummary(w*factor(sex) ~ N + Percent() + mean, data = dt)


  # Create if individuals own child or no

dt <- dt %>% 
  mutate(child = as.numeric(ownchild >= 1))

# Looking for hourly wage of individuals with children and without children data summary
datasummary(w * factor(child) ~ N +Percent() + mean, data = dt)


dt <- dt[sex == 1, gender := "Male"][sex == 2, gender := "Female"]

# Looking for data summary of individuals per each gender with children
datasummary(w * as.factor(gender) * factor(child) ~ N + Percent() + mean, data = dt)

# Checking hourly wage education level and gender data summary
datasummary(w* as.factor(educ)*as.factor(gender) ~ N + Percent() + mean, data = dt)

# Checking race summary
datasummary(as.factor(race) ~ N, data = dt)

# Checking race summary
datasummary(as.factor(marital) ~ N, data = dt)

# Add new variable for marital status, if married then 1 else 0
dt$marital_status <- ifelse(dt$marital <= 3, 1, 0)

datasummary(w* as.factor(educ)*as.factor(gender) ~ N + Percent() + mean, data = dt)

```




```{r include=FALSE}

# Figures are put in the Appendix

# Male hourly wage histogram
hist_w_m <- ggplot(data=dt[sex == 1], aes(x=w)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 5, boundary=0, fill = "#440154", color = "white", size = 0.2, alpha = 0.5,  show.legend=F, na.rm=TRUE) +
  labs(x = "Male Hourly Wage",y = "Percent")+
  theme_bw() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_y_continuous(expand = c(0.01,0.01),labels = scales::percent_format(accuracy = 1))

# Female hourly wage histogram
hist_w_f <- ggplot(data=dt[sex == 2], aes(x=w)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 5, boundary=0, fill = "#440154", color = "white", size = 0.2, alpha = 0.5,  show.legend=F, na.rm=TRUE) +
  labs(x = "Female Hourly Wage",y = "Percent")+
  theme_bw() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_y_continuous(expand = c(0.01,0.01),labels = scales::percent_format(accuracy = 1))

# Male age histogram

hist_age_m <- ggplot(data=dt[sex == 1], aes(x=age)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 5, boundary=0, fill = "#440154", color = "white", size = 0.2, alpha = 0.5,  show.legend=F, na.rm=TRUE) +
  labs(x = "Male Age Distribution",y = "Percent") +
  theme_bw() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_x_continuous(breaks = seq(15,70, 5)) +
  scale_y_continuous(expand = c(0.01,0.01),labels = scales::percent_format(accuracy = 1)) 

# Female age historam
hist_age_f <- ggplot(data=dt[sex == 2], aes(x=age)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 5, boundary=0, fill = "#440154", color = "white", size = 0.2, alpha = 0.5,  show.legend=F, na.rm=TRUE) +
  labs(x = "Female Age Distribution",y = "Percent") +
  theme_bw() +
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_x_continuous(breaks = seq(15,70, 5)) +
  scale_y_continuous(expand = c(0.01,0.01),labels = scales::percent_format(accuracy = 1)) 

# Box plots and jitter
# Box plot of hourly wage for each gender
jitter_gender <- ggplot(dt,aes(factor(gender), w, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Gender", y = "Hourly Wage")

# Box plot of hourly wage for levels of education
jitter_edu <- ggplot(dt,aes(factor(grade92), w, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Education", y = "Hourly Wage") + 
  scale_x_discrete(labels = c("Bachelors", "Masters", "Professional", "PhD"))

# Box plot of hourly wage for work sector
jitter_class <- ggplot(dt,aes(factor(class), w, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw()+
  theme(legend.position = "none", axis.text.x = element_text(angle= 45, vjust=.5)) +
  labs(x = "Working Sector", y = "Hourly Wage")

# Box plot for hourly wage if the individual has a child or no
jitter_child <- ggplot(dt,aes(factor(child), w, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("No", "Yes")) +
  labs(x = "Child", y = "Hourly Wage")

# Box plot for hourly wage if the individual is married or not
jitter_married <- ggplot(dt,aes(factor(marital_status), w, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("No", "Yes")) +
  labs(x = "Married", y = "Hourly Wage")

# Two variables boxplots
# Box plot of hourly wage for education level per gender 
boxplot_edu_gender <- ggplot(dt, aes(x = factor(grade92), y = w, fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Education Levels",y = "Wage per Hour in USD", color = "Gender", fill = "Gender") + 
  theme_bw() +
  theme(legend.position = "top") +
  scale_x_discrete(labels = c("Bachelors", "Masters", "Professional", "PhD"))

# Box plot of hourly wage for education level per gender 
boxplot_edu_married <- ggplot(dt, aes(x = factor(grade92), y = w, fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Education Levels",y = "Wage per Hour in USD", color = "Gender", fill = "Gender") + 
  theme_bw() +
  theme(legend.position = "top") +
  scale_x_discrete(labels = c("Bachelors", "Masters", "Professional", "PhD"))

# Box plot of hourly wage for child per gender 
boxplot_child_gender <- ggplot(dt, aes(x = factor(child), y = w, fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Child",y = "Wage per Hour in USD", color = "Gender", fill = "Gender") + 
  theme_bw() +
  theme(legend.position = "top") +
  scale_x_discrete(labels = c("No", "Yes"))

# Box plot of hourly wage for Working sector per gender
boxplot_class_gender <- ggplot(dt, aes(x = factor(class), y = w, fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Working Sector",y = "Wage per Hour in USD", color = "Gender", fill = "Gender") + 
  theme_bw() +
  theme(legend.position = "top", axis.text.x = element_text(angle= 45, vjust=.5))

# Box plot of hourly wage for marital status per gender
boxplot_married_gender <- ggplot(dt, aes(x = factor(marital_status), y = w, fill = factor(gender), color=factor(gender))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Married",y = "Wage per Hour in USD", color = "Gender", fill = "Gender") + 
  theme_bw() +
  theme(legend.position = "top") +
  scale_x_discrete(labels = c("No", "Yes"))




scatter_age <- ggplot( dt , aes(x = age, y = w)) +
    geom_point(size=0.5,alpha=0.6, na.rm = T, color = "#440154") +
    geom_smooth(method="loess" , formula = y ~ x , na.rm = T, color = "#fde725" )+
    theme_bw() +
    scale_color_viridis(option = "D", discrete = TRUE) +
    scale_fill_viridis(option = "D", discrete = TRUE) +
    labs(x = "Age",y = "Wage per Hour in USD", color = "Gender", fill = "Gender")


scatter_edu <- ggplot( dt , aes(x = grade92, y = w)) +
  geom_point(size=0.9, alpha=0.8, na.rm = T, color = "#440154") +
  geom_smooth(method="lm" , formula = y ~ x , na.rm = T, color = "#fde725")+
  theme_bw() +
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Education Levels",y = "Wage per Hour in USD") +
  scale_x_continuous(labels = c("Bachelors", "Masters", "Professional", "PhD")) +
  theme(axis.text.x = element_text(angle= 45, vjust=.5))


```


# DA3 Assignment 1

### 1.Introduction

This assignment presents earnings per hour of **this** occpuation for the ones who has more than associate degree or occupational /vocational 


### 2. Data

### 3. Regressions

### 4. Performance of Models

### 5. Prediction 
### 5. Summary
```{r include=FALSE}

# Creating 5% and 95% 
P05 <- function(x){ quantile(x,.05,na.rm=T)}
P95 <- function(x){ quantile(x,.95,na.rm=T)}

# Data Summary
summary_table <- datasummary(
  (`Weekly earnings` = earnwke) + 
  (`Weekly hours worked` = uhours) + 
  (`Earning per hour` = w) + 
  (`Female` = female) +
  (`BA Degree` = ed_BA) + 
  (`MA Degree` = ed_MA) + 
  (`Professional Degree` = ed_Profess) + 
  (`PhD` = ed_PhD) + 
  (`Age` = age) + 
  (`Work in Private Sector` = privt_sec) + 
  (`Has child` = child) ~ (Median + Mean + SD + Min + Max + P05 + P95 + N), 
  data = dt, 
  title = "Descriptive Summary Statistics" ) %>% 
  kable_styling(latex_options = c("HOLD_position","scale_down"))

```


```{r include=FALSE}
# Regressions
# Simple Model one

m1 <- as.formula(w ~ ed_MA + ed_Profess + ed_PhD)
m2 <- as.formula(w ~ ed_MA + ed_Profess + ed_PhD + age + agesq)
m3 <- as.formula(w ~ ed_MA + ed_Profess + ed_PhD + age + agesq + female + privt_sec, child)
m4 <- as.formula(w ~ ed_MA + ed_Profess + ed_PhD + age + agesq + female + privt_sec + female * ed_MA + female * ed_Profess + female * ed_PhD + female * age + female * agesq + female * privt_sec + female * child)

reg1 <- feols(m1, data = dt, vcov = 'hetero')
reg2 <- feols(m2, data = dt, vcov = 'hetero')
reg3 <- feols(m3, data = dt, vcov = 'hetero')

# Complex Regression
reg4 <- feols(m4, data = dt, vcov = 'hetero')

```

```{r include=FALSE}

# Adding variables names
variable_names <- c('(Intercept)' = 'Intercept',
                    'w' = 'Hourly wage',
                    'ed_MA' = 'MA Degree',
                    'ed_Profess' = 'Professional Degree',
                    'ed_PhD' = 'PhD',
                    'age' = 'Age',
                    'agesq' = 'Age Squared',
                    'female' = 'Female',
                    'privt_sec' = 'Private Sector',
                    'child' = 'Has Child')
```


```{r echo=FALSE}
# evaluation of the models: using all the sample

fitstat_register("k", function(x){length( x$coefficients ) - 1}, "No. Variables")

etable( 'M1' = reg1 , 'M2' = reg2 , 'M3' = reg3 , 'M4' = reg4 , 
        dict = variable_names,
        fitstat = c('aic','bic','rmse','r2','n','k') )


```

```{r include=FALSE}

# Simple k-fold cross validation setup:
# set number of folds to use (must be less than the no. observations)
k <- 4

# Model 1
set.seed(1238)
cv1 <- train(m1, dt, method = "lm", trControl = trainControl(method = "cv", number = k))

# Model 2
set.seed(1238)
cv2 <- train(m2, dt, method = "lm", trControl = trainControl(method = "cv", number = k))

# Model 3
set.seed(1238)
cv3 <- train(m3, dt, method = "lm", trControl = trainControl(method = "cv", number = k))

# Model 4
set.seed(1238)
cv4 <- train(m4, dt, method = "lm", trControl = trainControl(method = "cv", number = k))


# Calculate RMSE for each fold and the average RMSE as well
cv <- c("cv1", "cv2", "cv3", "cv4")
rmse_cv <- c()

for(i in 1:length(cv)){
  rmse_cv[i] <- sqrt((get(cv[i])$resample[[1]][1]^2 +
                       get(cv[i])$resample[[1]][2]^2 +
                       get(cv[i])$resample[[1]][3]^2 +
                       get(cv[i])$resample[[1]][4]^2)/4)
}


# summarize results
cv_mat <- data.frame(rbind(cv1$resample[4], "Average"),
           rbind(cv1$resample[1], rmse_cv[1]),
           rbind(cv2$resample[1], rmse_cv[2]),
           rbind(cv3$resample[1], rmse_cv[3]),
           rbind(cv4$resample[1], rmse_cv[4])
           )

colnames(cv_mat)<-c("Resample","Model1", "Model2", "Model3", "Model4")
cv_mat 

```


```{r echo=FALSE}
# Model complexity and out-of-sample RMSE performance
m_comp <- c()
models <- c("reg1", "reg2", "reg3", "reg4")
for( i in 1 : length(cv) ){
  m_comp[ i ] <- length( get( models[i] )$coefficient  - 1 ) 
}

m_comp <- tibble( model = models , 
                  complexity = m_comp,
                  RMSE = rmse_cv )

ggplot( m_comp , aes( x = complexity , y = RMSE ) ) +
  geom_point(color='red',size=2) +
  geom_line(color='blue',size=0.5)+
  labs(x='Number of explanatory variables',y='Averaged RMSE on test samples',
       title='Prediction performance and model compexity') +
  theme_bw()
```



```{r}
# Select Model 3

###############
# 5C) Prediction
#   Compare model1 and model3 to predict our the hourly wage


dt <- dt %>% select(grade92, age, female, w, ed_BA, ed_MA, ed_Profess, ed_PhD, agesq, privt_sec, child)

```


\newpage
### Appendix
### Descriptive Data Summary

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Descriptive Data Summary
summary_table

```


\newpage
### Histograms

```{r echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, fig.height=8, fig.width=8}

# Histograms

grid.arrange( grobs = list(hist_w_f, hist_w_m, hist_age_f, hist_age_m), ncol = 2)

```


\newpage
### Boxplots



```{r echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, fig.height=8, fig.width=8}

grid.arrange( grobs = list(jitter_gender, jitter_child, jitter_edu, jitter_class ), ncol = 2)

```

\newpage
### Boxplots

```{r echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, fig.height=8, fig.width=8}

grid.arrange( grobs = list(boxplot_edu_gender, boxplot_class_gender, boxplot_child_gender, boxplot_married_gender), ncol = 2)

```

\newpage
### Boxplots

```{r echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, fig.height=8, fig.width=8}

grid.arrange( grobs = list(scatter_edu, scatter_age), ncol = 2)

```

