---
title: "Data Analysis 3 : Assignment II"
author: "Ghazal"
geometry : margin=1.7cm
fontsize: 9pt
output: 
  pdf_document:
  extra_dependencies: ["flafter"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Clearing the environment
rm(list=ls())
# Loading the Libraries
library(tidyverse)
library(caret)
library(modelsummary)
library(stargazer)
library(xtable)
library(rattle)
library(kableExtra)
library(data.table)
library(ggplot2)
library(GGally)
library(gridExtra)
library(knitr)
library(viridis)
library(directlabels)
library(Hmisc)
library(cowplot)
library(ranger)
library(glmnet)
library(grid)
library(skimr)
library(gbm)
library(fixest)

```



```{r include=FALSE}

getwd()

setwd("/Users/ghazalayobi/DA3/A2")
path <- "/Users/ghazalayobi/DA3/A2"

#location folders
data_in  <- paste0(path,"/data/raw/")
data_out <- paste0(path,"/data/clean/")
output <- paste0(path, "/output/")

dfx <- read_csv("/Users/ghazalayobi/DA3/A2/data/clean/airbnb_ny_cleaned.csv")
# github link for clean data()
df <- subset(dfx, select = -c(latitude, longitude))

source("https://raw.githubusercontent.com/ghazalayobi/DA3/main/da_helper_functions.R")
source("https://raw.githubusercontent.com/ghazalayobi/DA3/main/theme_bg.R")

# checking for missing variables
to_filter <- sort(sapply(df, function(x) sum(is.na(x)/nrow(df)*100)))
to_filter[to_filter > 0]

# quick look at data
#glimpse(df)
#skim(df)

```



```{r include=FALSE}
# Checking for data summaries
# Accommodates Summary
sum_accomm <- datasummary(price* (`Accommodates` = as.factor(n_accommodates)) ~ N + min + max + 
                            Percent() + mean, data = df, title = "Accommodates Summary")

# Number of Beds Summary
sum_beds <- datasummary(price* (`Beds` = as.factor(n_beds)) ~ N + min + max + 
                            Percent() + mean, data = df, title = "Beds Summary")

# Number of Beds Summary
sum_bedrooms <- datasummary(price* (`Bedrooms` = as.factor(n_bedrooms)) ~ N + min + max + 
                            Percent() + mean, data = df, title = "Bedrooms Summary")

# Room type Summary
sum_room_type <- datasummary(price* (`Room Type` = as.factor(f_room_type)) ~ N + min + max + 
                               Percent() + mean, data = df, title = "Room Type Summary")

# Property Type Summary
sum_property_type <- datasummary(price* (`Property Type` = as.factor(f_property_type)) ~ N + min + max + 
                                   Percent() + mean, data = df, title = "Property Type Summary")

# Host response time Summary
sum_host_res_time <- datasummary(price* (`Room Type` = as.factor(f_host_response_time)) ~ N + min + max + 
                                   Percent() + mean, data = df, title = "Host Response Time Summary")

# Minimum Nights summary
sum_nnights <- datasummary((`Min Nights` = n_minimum_nights) ~ N + min + 
                             max + mean, data = df, title = "Minimum nights Summary")

# Neighborhood summary
sum_neighbourhood <- datasummary((`Neighbourhood` = neighbourhood_cleansed) ~ N + min + 
                             max + mean, data = df, title = "Neighbourhood Summary")

# Neighborhood group summary
sum_neighbourhood_group <- datasummary((`Neighbourhood Group` = neighbourhood_group_cleansed) ~ N + min + 
                             max + mean, data = df, title = "Neighbourhood Group Summary")
```

```{r }
# Histograms

# price -> skewed distribution with long right tail
hist_price <- ggplot(data=df, aes(x=price)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 10, boundary=0,
                 color = "white", fill = "#440154", alpha = 0.7) +
  coord_cartesian(xlim = c(0, 500)) +
  labs(x = "Price (US dollars)",y = "Percent")+
  scale_y_continuous(expand = c(0.00,0.00),limits=c(0, 0.10), breaks = seq(0, 0.10, by = 0.03), labels = scales::percent_format(1)) +
  scale_x_continuous(expand = c(0.00,0.00),limits=c(0,500), breaks = seq(0,500, 50)) +
  theme_bw() 
hist_price

# lnprice -> closer to a normal distribution
hist_ln_price <- ggplot(data=df, aes(x=ln_price)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 0.15,
                 color = "white", fill = "#440154", alpha = 0.7) +
  coord_cartesian(xlim = c(3.5, 6.5)) +
  scale_y_continuous(expand = c(0.00,0.00),limits=c(0, 0.15), breaks = seq(0, 0.10, by = 0.05), labels = scales::percent_format(5L)) +
  labs(x = "ln(price, US dollars)",y = "Percent")+
  theme_bw() 
hist_ln_price

```


```{r}
# Box plots and jitter for one variable

# Boxplot for the number of accommodates
jitter_accomm <- ggplot(df,aes(factor(n_accommodates), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Nr of Accommodates", y = "Price") +
  ggtitle("Nr of Accommodates ")
jitter_accomm

# Boxplot for the Property type
jitter_property_type <- ggplot(df,aes(factor(f_property_type), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Property Type", y = "Price") +
  ggtitle("Property Type ")
jitter_property_type


# Boxplot for the room type
jitter_room_type <- ggplot(df,aes(factor(f_room_type), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Room Type", y = "Price") +
  ggtitle("Room Type ")
jitter_room_type

# Boxplot for the Host response time
jitter_host_res_time <- ggplot(df,aes(factor(f_host_response_time), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Host response time", y = "Price") +
  ggtitle("Host Response Time ")
jitter_host_res_time

# boxplot for the grouped neighborhood
jitter_neighbourhood_group <- ggplot(df,aes(factor(f_neighbourhood_group_cleansed), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Neighbourhood group", y = "Price") +
  ggtitle("Neighbourhood Group")
jitter_neighbourhood_group

# Boxplot for the number of bathrooms
jitter_bathrooms <- ggplot(df,aes(factor(n_bathrooms), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Nr Bathrooms", y = "Price") +
  ggtitle("Number of Bathrooms Price Distribution")
jitter_bathrooms

# Boxplot for the number of bedrooms
jitter_bedrooms <- ggplot(df,aes(factor(n_bedrooms), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Nr bedrooms", y = "Price") +
  ggtitle("Number of Bedrooms Price Distribution")
jitter_bedrooms

# Boxplot for the number of beds
jitter_beds <- ggplot(df,aes(factor(n_beds), price, color = "#440154" )) + 
  geom_boxplot(alpha = 0.1, frame = FALSE) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.2) +
  scale_color_viridis(option = "D", discrete = TRUE)+
  scale_fill_viridis(option = "D", discrete = TRUE) +
  theme_bw() +
  theme(legend.position = "none", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  labs(x = "Nr beds", y = "Price") +
  ggtitle("Number of Beds Price Distribution")
jitter_beds


```


```{r}
# Two variables boxplots
# property and wifi price distribution
boxplot_pr_wifi <- ggplot(df, aes(x = factor(property_type), y = price, fill = factor(d_wifi), color=factor(d_wifi))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Property Type",y = "Price", color = "wifi", fill = "wifi") + 
  theme_bw() +
  theme(legend.position = "top", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  ggtitle("Property type and wifi price distribution")

boxplot_pr_wifi

# property type and kitchen price distribution
boxplot_pr_kitchen <- ggplot(df, aes(x = factor(property_type), y = price, fill = factor(d_kitchen), color=factor(d_kitchen))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Property Type",y = "Price", color = "Kitchen", fill = "Kitchen") + 
  theme_bw() +
  theme(legend.position = "top", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  ggtitle("Property type and Kitchen price distribution")

boxplot_pr_kitchen

# property type and kitchen price distribution
boxplot_accomm_pr <- ggplot(df, aes(x = factor(n_accommodates), y = price, fill = factor(f_property_type), color=factor(f_property_type))) +
  geom_boxplot(alpha=0.6, na.rm=T, outlier.shape = NA, width = 0.8) +
  stat_boxplot(geom = "errorbar", width = 0.8, size = 0.3, na.rm=T)+
  scale_color_viridis(option = "D", discrete = TRUE) +
  scale_fill_viridis(option = "D", discrete = TRUE) +
  labs(x = "Accommodates (Person)",y = "Price (USD Dollar)", color = "Property Type", fill = "Property Type") + 
  theme_bw() +
  theme(legend.position = "top", panel.border = element_blank(), axis.text=element_text(size=8), plot.title = element_text(size = 12L, face = "bold", hjust = 0.5) ) +
  ggtitle("Property type and accommodates price distribution")

boxplot_accomm_pr


```



```{r}

##################################
# Part II 
################################
# Defining variables

# define variables
basic_lev <- c("n_accommodates", "f_property_type", "n_beds", "n_days_since", "flag_days_since")

# Factorized variables
basic_add <- c("f_bathroom", "f_neighbourhood_group_cleansed", "f_host_response_time")

# reviews
reviews <- c("f_number_of_reviews", "n_review_scores_rating", "n_review_scores_rating", "n_reviews_per_month")

# higher orders
poly_lev <- c("n_accommodates2", "n_days_since2", "n_days_since3")

# Dummy Variables 
dummies <- grep("^d_.*", names(df), value = TRUE)


```

```{r eval=FALSE, include=FALSE}
# Look for interactions         

# Plot interactions between property type and all dummies
sapply(dummies, function(x){
  p <- price_diff_by_variables2(df, "property_type", x, "Property type", x)
  print(p)
})

price_diff_by_variables(df, "property_type", "d_air_conditioning")


```

```{r}
#Look up room type interactions

p1 <- price_diff_by_variables2(df, "f_property_type", "d_air_conditioning", "Property Type", "Air Conditioning")
p2 <- price_diff_by_variables2(df, "f_property_type", "d_elevator", "Property Type", "Elevator")
p3 <- price_diff_by_variables2(df, "f_property_type", "d_kitchen", "Property Type", "Kitchen")
p4 <- price_diff_by_variables2(df, "f_property_type", "d_essentials", "Property Type", "Essential")
p5 <- price_diff_by_variables2(df, "f_property_type", "d_pool", "Property Type", "Pool")
p6 <- price_diff_by_variables2(df, "f_property_type", "d_washer", "Property Type", "Washer")
p7 <- price_diff_by_variables2(df, "f_property_type", "d_wifi", "Property Type", "Wifi")
p8 <- price_diff_by_variables2(df, "f_property_type", "d_tv", "Property Type", "TV")
p9 <- price_diff_by_variables2(df, "f_property_type", "d_patio_or_balcony", "Property Type", "Balcony")
p10 <- price_diff_by_variables2(df, "f_property_type", "d_gym", "Property Type", "Gym")
p11 <- price_diff_by_variables2(df, "f_property_type", "d_dryer", "Property Type", "Dryer")
p12 <- price_diff_by_variables2(df, "f_property_type", "d_stove", "Property Type", "Stove")



g_interactions <- plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, nrow=4, ncol=3) 
g_interactions


```


```{r}

# based on suggested grpaphs
X1 <- c("f_property_type * n_accommodates", "f_property_type * f_host_response_time")


# Additional dummies based on graphs suggestion
X2  <- c("f_property_type*d_air_conditioning", 
         "f_property_type*d_elevator",
         "f_property_type*d_dryer",
         "f_property_type*d_washer",
         "f_property_type*d_wifi",
         "f_property_type*d_kitchen", 
         "f_property_type*d_breakfast")


# all dummies with property type
X3  <- c("f_property_type*f_neighbourhood_group_cleansed", "n_accommodates*f_neighbourhood_group_cleansed",
         paste0("(f_property_type) * (",
                paste(dummies, collapse=" + "),")"))

```

```{r}


# Create models in levels models: 1-8
modellev1 <- " ~ n_accommodates"
modellev2 <- paste0(" ~ ",paste(basic_lev,collapse = " + "))
modellev3 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews),collapse = " + "))
modellev4 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews, poly_lev),collapse = " + "))
modellev5 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews,poly_lev, X1),collapse = " + "))
modellev6 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews,poly_lev, X1, X2),collapse = " + "))
modellev7 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews,poly_lev, X1, X2, dummies),collapse = " + "))
modellev8 <- paste0(" ~ ",paste(c(basic_lev,basic_add,reviews,poly_lev, X1, X2, dummies, X3),collapse = " + "))

```

```{r}

# Separate hold-out set #
#----------------------------------------
# create a holdout set (20% of observations)
smp_size <- floor(0.2 * nrow(df))

# Set the random number generator: It will make results reproducable
set.seed(12345)

# A) create ids:
# 1) seq_len: generate regular sequences
# 2) sample: select random rows from a table
holdout_ids <- sample(seq_len(nrow(df)), size = smp_size)
df$holdout <- 0
df$holdout[holdout_ids] <- 1

#Hold-out set Set
data_holdout <- df %>% filter(holdout == 1)

#Working data set
data_work <- df %>% filter(holdout == 0)
```



```{r}
####################################
# B) Utilizing the Working data set:
#   a) estimating measures on the whole working sample (R2,BIC,RMSE)
#   b) Doing K-fold cross validation to get proper Test RMSE

## K = 5
k_folds=5
# Create the folds
set.seed(12345)

folds_i <- sample(rep(1:k_folds, length.out = nrow(data_work) ))
# Create results
model_results_cv <- list()


for (i in (1:8)){
  model_name <-  paste0("modellev",i)
  model_pretty_name <- paste0("(",i,")")

  yvar <- "price"
  xvars <- eval(parse(text = model_name))
  formula <- formula(paste0(yvar,xvars))

  # Initialize values
  rmse_train <- c()
  rmse_test <- c()

  model_work_data <- lm(formula,data = data_work)
  BIC <- BIC(model_work_data)
  nvars <- model_work_data$rank -1
  r2 <- summary(model_work_data)$r.squared

  # Do the k-fold estimation
  for (k in 1:k_folds) {
    test_i <- which(folds_i == k)
    # Train sample: all except test_i
    data_train <- data_work[-test_i, ]
    # Test sample
    data_test <- data_work[test_i, ]
    # Estimation and prediction
    model <- lm(formula,data = data_train)
    prediction_train <- predict(model, newdata = data_train)
    prediction_test <- predict(model, newdata = data_test)

    # Criteria evaluation
    rmse_train[k] <- mse_lev(prediction_train, data_train[,yvar] %>% pull)**(1/2)
    rmse_test[k] <- mse_lev(prediction_test, data_test[,yvar] %>% pull)**(1/2)

  }

  model_results_cv[[model_name]] <- list(yvar=yvar,xvars=xvars,formula=formula,model_work_data=model_work_data,
                                         rmse_train = rmse_train,rmse_test = rmse_test,BIC = BIC,
                                         model_name = model_pretty_name, nvars = nvars, r2 = r2)
}

model <- lm(formula,data = data_train)
prediction_train <- predict(model, newdata = data_train)
prediction_test <- predict(model, newdata = data_test)

skim(data_train$ln_days_since)

t1 <- imap(model_results_cv,  ~{
  as.data.frame(.x[c("rmse_test", "rmse_train")]) %>%
    dplyr::summarise_all(.funs = mean) %>%
    mutate("model_name" = .y , "model_pretty_name" = .x[["model_name"]] ,
           "nvars" = .x[["nvars"]], "r2" = .x[["r2"]], "BIC" = .x[["BIC"]])
}) %>%
  bind_rows()
t1
column_names <- c("Model", "N predictors", "R-squared", "BIC", "Training RMSE",
                 "Test RMSE")

# R2, BIC on full work data-n.
# In sample rmse: average on training data; avg test : average on test data

OLS_models <- t1 %>%
  select("model_pretty_name", "nvars", "r2" , "BIC", "rmse_train", "rmse_test")
colnames(OLS_models) <- column_names
print(xtable(OLS_models, type = "latex", digits=c(0,0,0,2,0,2,2)), file = paste0(output, "OLS_models.tex"),
      include.rownames=FALSE, booktabs=TRUE, floating = FALSE)

# RMSE training vs test graph
t1_levels <- t1 %>%
  dplyr::select("nvars", "rmse_train", "rmse_test") %>%
  gather(var,value, rmse_train:rmse_test) %>%
  mutate(nvars2=nvars+1) %>%
  mutate(var = factor(var, levels = c("rmse_train", "rmse_test"),
                      labels = c("RMSE Training","RMSE Test")))

model_result_plot_levels <- ggplot(data = t1_levels,
                                   aes(x = factor(nvars2), y = value, color=factor(var), group = var)) +
  geom_line(size=1,show.legend=FALSE, na.rm = TRUE) +
  scale_color_manual(name="",
                     values=c("blue","red")) +
  #scale_y_continuous(name = "RMSE", limits = c(26, 50), breaks = seq(26,50, 2)) +
  #scale_x_discrete( name = "Number of coefficients", expand=c(0.01, 0.01)) +
  geom_dl(aes(label = var),  method = list("last.points", dl.trans(x=x-1), cex=0.4)) +
  #scale_colour_discrete(guide = 'none') +
  theme_bw()
model_result_plot_levels

# Model 7 gives the best result based on the RMSE result
```


```{r}

# Set lasso tuning parameters:
#----------------------------------------------------
# a) basic setup
train_control <- trainControl( method = "cv", number = k_folds)
# b) tell the actual lambda (penalty parameter) to use for lasso
tune_grid     <- expand.grid("alpha" = c(1), "lambda" = seq(0.05, 1, by = 0.05))
# c) create a formula

# creating three predictors to be used for OLS, LASSO and Random forest
predictors_1 <- c(basic_lev, basic_add, reviews, dummies)
predictors_2 <- c(basic_lev,basic_add,reviews,poly_lev, X1, X2, dummies) #Model 7, best model based on CV RMSE
predictors_E <- c(basic_lev, basic_add, reviews, poly_lev, dummies, X1, X2, X3) # Model 8 and finding observations where there is no missing data

```


```{r}

# OLS BASIC           
#################################

# Using OLS for the Basic variables
set.seed(12345)
system.time({
  ols_model <- train(
    formula(paste0("price ~", paste0(predictors_2, collapse = " + "))),
    data = data_work,
    method = "lm",
    trControl = train_control
  )
})

ols_model_coeffs <-  ols_model$finalModel$coefficients
ols_model_coeffs_df <- data.frame(
  "variable" = names(ols_model_coeffs),
  "ols_coefficient" = ols_model_coeffs
) %>%
  mutate(variable = gsub("`","",variable))


```



```{r}

# LASSO               
#-------------------------------------------------

# setting seed
set.seed(12345)
system.time({
  lasso_model <- caret::train(
    formula(paste0("price ~", paste0(predictors_2, collapse = " + "))),
    data = data_work,
    method = "glmnet",
    tuneGrid =  expand.grid("alpha" = 1, "lambda" = seq(0.01, 0.25, by = 0.01)),
    preProcess = c("center", "scale"),
    trControl = train_control
  )
})

print(lasso_model$bestTune$lambda)

lasso_coeffs <- coef(
  lasso_model$finalModel,
  lasso_model$bestTune$lambda) %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column(var = "variable") %>% 
  rename(coefficient = `s1`)  # the column has a name "1", to be renamed

print(lasso_coeffs)

lasso_coeffs_nz<-lasso_coeffs %>%
  filter(coefficient!=0)
print(nrow(lasso_coeffs_nz))

# Evaluate model. CV error:
lasso_cv_rmse <- lasso_model$results %>%
  filter(lambda == lasso_model$bestTune$lambda) %>%
  dplyr::select(RMSE)
print(lasso_cv_rmse[1, 1])

```



```{r}
# CART        
#-------------------------------------------
# setting seed
set.seed(12345)
system.time({
  cart_model <- train(
    formula(paste0("price ~", paste0(predictors_1, collapse = " + "))),
    data = data_work,
    method = "rpart",
    tuneLength = 10,
    trControl = train_control
  )
})

fancyRpartPlot(cart_model$finalModel, sub = "")
```



```{r}
# RANDOM FOREST     
#-------------------------------------------
# using all variables without their functional forms. Using predictor 1
# setting seed
# set tuning
tune_grid <- expand.grid(
  .mtry = c(8),
  .splitrule = "variance",
  .min.node.size = c(50)
)

# set seed
set.seed(12345)
system.time({
rf_model_1 <- train(
  formula(paste0("price ~", paste0(predictors_1, collapse = " + "))),
  data = data_train,
  method = "ranger",
  trControl = train_control,
  tuneGrid = tune_grid,
  importance = "impurity"
)
})
rf_model_1
```


```{r}
# RANDOM FOREST     
#-------------------------------------------
# auto tuning
set.seed(12345)
system.time({
   rf_model_2auto <- train(
     formula(paste0("price ~", paste0(predictors_1, collapse = " + "))),
     data = data_train,
     method = "ranger",
     trControl = train_control,
     importance = "impurity"
   )
})
rf_model_1auto 
```


```{r}
library(gbm)
# GBM              
#################################

#### Basic GMB model
gbm_grid <-  expand.grid(interaction.depth = c(1, 5, 10), # complexity of the tree
                         n.trees = (4:10)*50, # number of iterations, i.e. trees
                         shrinkage = 0.1, # learning rate: how quickly the algorithm adapts
                         n.minobsinnode = 20 # the minimum number of training set samples in a node to commence splitting
)


set.seed(1234)
system.time({
  gbm_model <- train(formula(paste0("price ~", paste0(predictors_2, collapse = " + "))),
                     data = data_work,
                     method = "gbm",
                     trControl = train_control,
                     verbose = FALSE,
                     tuneGrid = gbm_grid)
})
gbm_model



# Turning parameter choice 1
result_1 <- matrix(c(
  rf_model$finalModel$mtry,
  rf_model$finalModel$min.node.size
),
nrow=1, ncol=2,
dimnames = list("Model A",
                c("Min vars","Min nodes"))
)
kable(x = result_1, format = "latex", digits = 3) %>%
  cat(.,file= paste0(output,"rf_models_turning_choices.tex"))


```


```{r}
#################################
#          FINAL MODELS         #
#################################
final_models <-
  list("OLS" = ols_model,
       "LASSO" = lasso_model,
       "CART" = cart_model,
       "Random forest"= rf_model,
       "GBM"  = gbm_model
       )

results <- resamples(final_models) %>% summary()


# Save output --------------------------------------------------------
# Model selection is carried out on this CV RMSE

result_4 <- imap(final_models, ~{
  mean(results$values[[paste0(.y,"~RMSE")]])
}) %>% unlist() %>% as.data.frame() %>%
  rename("CV RMSE" = ".")

result_4

kable(x = result_4, format = "latex", digits = 3, booktabs=TRUE, linesep = "") %>%
  cat(.,file= paste0(output,"final_models_cv_rmse.tex"))




# evaluate preferred model on the holdout set -----------------------------

result_5 <- map(final_models, ~{
  RMSE(predict(.x, newdata = data_holdout), data_holdout[["price"]])
}) %>% unlist() %>% as.data.frame() %>%
  rename("Holdout RMSE" = ".")

result_5

kable(x = result_5, format = "latex", digits = 3, booktabs=TRUE, linesep = "") %>%
  cat(.,file= paste0(output,"final_models_houldout_rmse.tex"))

```

```{r}

###################################################
# Diagnsotics #
###################################################


#########################################################################################
# Variable Importance Plots -------------------------------------------------------
#########################################################################################
# first need a function to calculate grouped varimp
group.importance <- function(rf.obj, groups) {
  var.imp <- as.matrix(sapply(groups, function(g) {
    sum(importance(rf.obj)[g], na.rm = TRUE)
  }))
  colnames(var.imp) <- "MeanDecreaseGini"
  return(var.imp)
}


rf_model_var_imp <- importance(rf_model$finalModel)/1000
rf_model_var_imp_df <-
  data.frame(varname = names(rf_model_var_imp),imp = rf_model_var_imp) %>%
  arrange(desc(imp)) %>%
  mutate(imp_percentage = imp/sum(imp))

```

```{r}
##############################
# full varimp plot, top 10 only
##############################

rf_model_var_imp_plot_b <- ggplot(rf_model_var_imp_df[1:50,], aes(x=reorder(varname, imp), y=imp_percentage)) +
  geom_point(color ="cyan4", size=1) +
  geom_segment(aes(x=varname,xend=varname,y=0,yend=imp_percentage), color="cyan4", size=0.75) +
  ylab("Importance (Percent)") +
  xlab("Variable Name") +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic() +
  theme(axis.text.x = element_text(size=6), axis.text.y = element_text(size=6),
        axis.title.x = element_text(size=6), axis.title.y = element_text(size=6))
rf_model_var_imp_plot_b

save_fig("Fig9-rf-varimp-top10",output, "small")
```

```{r}
##############################
# 2) varimp plot grouped
##############################
# grouped variable importance - keep binaries created off factors together

varnames <- rf_model$finalModel$xNames
f_neighbourhood_cleansed_varnames <- grep("f_neighbourhood_cleansed",varnames, value = TRUE)
f_room_type_varnames <- grep("f_room_type",varnames, value = TRUE)

groups <- list(f_neighbourhood_cleansed=f_neighbourhood_cleansed_varnames,
               f_room_type = f_room_type_varnames,
               f_bathroom = "f_bathroom",
               n_days_since = "n_days_since",
               n_accommodates = "n_accommodates",
               n_beds = "n_beds")

rf_model_var_imp_grouped <- group.importance(rf_model$finalModel, groups)
rf_model_var_imp_grouped_df <- data.frame(varname = rownames(rf_model_var_imp_grouped),
                                            imp = rf_model_var_imp_grouped[,1])  %>%
  mutate(imp_percentage = imp/sum(imp))

rf_model_var_imp_grouped_plot <-
  ggplot(rf_model_var_imp_grouped_df, aes(x=reorder(varname, imp), y=imp_percentage)) +
  geom_point(color="cyan4", size=1) +
  geom_segment(aes(x=varname,xend=varname,y=0,yend=imp_percentage), color="cyan4", size=0.7) +
  ylab("Importance (Percent)") +   xlab("Variable Name") +
  coord_flip() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic() +
  theme(axis.text.x = element_text(size=6), axis.text.y = element_text(size=6),
        axis.title.x = element_text(size=6), axis.title.y = element_text(size=6))
rf_model_var_imp_grouped_plot

save_fig("Fig10-rf-varimp-group",output, "small")

```


```{r}
#########################################################################################
# Partial Dependence Plots -------------------------------------------------------
#########################################################################################

pdp_n_acc <- pdp::partial(rf_model, pred.var = "n_accommodates", pred.grid = distinct_(data_holdout, "n_accommodates"), train = data_train)
pdp_n_acc_plot <- pdp_n_acc %>%
  autoplot( ) +
  geom_point(color="cyan4", size=3) +
  geom_line(color="cyan4", size=1) +
  ylab("Predicted price") +
  xlab("Accommodates (persons)") +
  scale_x_continuous(limit=c(1,7), breaks=seq(1,7,1))+
  theme_classic()
pdp_n_acc_plot

save_fig("Fig11-gbm-pdp-n-accom", output, "small")



pdp_n_roomtype <- pdp::partial(rf_model, pred.var = "f_room_type", pred.grid = distinct_(data_holdout, "f_room_type"), train = data_train)
pdp_n_roomtype_plot <- pdp_n_roomtype %>%
  autoplot( ) +
  geom_point(color="cyan4", size=3) +
  ylab("Predicted price") +
  xlab("Room type") +
  scale_y_continuous(limits=c(60,130), breaks=seq(60,130, by=10)) +
  theme_classic()
pdp_n_roomtype_plot

save_fig("Fig12-gbm-pdp-roomtype", output, "small")




# Subsample performance: RMSE / mean(y) ---------------------------------------

# ---- cheaper or more expensive flats - not used in book
data_holdout_w_prediction <- data_holdout %>%
  mutate(predicted_price = predict(rf_model, newdata = data_holdout))



######### create nice summary table of heterogeneity
a <- data_holdout_w_prediction %>%
  mutate(is_low_size = ifelse(n_accommodates <= 3, "small apt", "large apt")) %>%
  group_by(is_low_size) %>%
  dplyr::summarise(
    rmse = RMSE(predicted_price, price),
    mean_price = mean(price),
    rmse_norm = RMSE(predicted_price, price) / mean(price)
  )


b <- data_holdout_w_prediction %>%
  group_by(f_neighbourhood_cleansed) %>%
  dplyr::summarise(
    rmse = RMSE(predicted_price, price),
    mean_price = mean(price),
    rmse_norm = rmse / mean_price
  )

c <- data_holdout_w_prediction %>%
  group_by(f_room_type) %>%
  dplyr::summarise(
    rmse = RMSE(predicted_price, price),
    mean_price = mean(price),
    rmse_norm = rmse / mean_price
  )


d <- data_holdout_w_prediction %>%
  dplyr::summarise(
    rmse = RMSE(predicted_price, price),
    mean_price = mean(price),
    rmse_norm = RMSE(predicted_price, price) / mean(price)
  )

# Save output
colnames(a) <- c("", "RMSE", "Mean price", "RMSE/price")
colnames(b) <- c("", "RMSE", "Mean price", "RMSE/price")
colnames(c) <- c("", "RMSE", "Mean price", "RMSE/price")
d<- cbind("All", d)
colnames(d) <- c("", "RMSE", "Mean price", "RMSE/price")

line1 <- c("Type", "", "", "")
line2 <- c("Apartment size", "", "", "")
line3 <- c("Borough", "", "", "")

result_3 <- rbind(line2, a, line1, c, line3, b, d) %>%
  transform(RMSE = as.numeric(RMSE), `Mean price` = as.numeric(`Mean price`),
            `RMSE/price` = as.numeric(`RMSE/price`))


result_3

options(knitr.kable.NA = '')
kable(x = result_3, format = "latex", booktabs=TRUE, linesep = "",digits = c(0,2,1,2), col.names = c("","RMSE","Mean price","RMSE/price")) %>%
  cat(.,file= paste0(output, "performance_across_subsamples.tex"))
options(knitr.kable.NA = NULL)


```

```{r}
###################################################
# FIGURES FOR FITTED VS ACTUAL OUTCOME VARIABLES #
###################################################

Ylev <- data_holdout[["price"]]

# Predicted values
prediction_holdout_pred <- as.data.frame(predict(gbm_model, newdata = data_holdout, interval="predict")) 

predictionlev_holdout <- cbind(data_holdout[,c("price","n_accommodates")],
                               prediction_holdout_pred)



# Create data frame with the real and predicted values
d <- data.frame(ylev=Ylev, predlev=predictionlev_holdout[,3] )
# Check the differences
d$elev <- d$ylev - d$predlev

# Plot predicted vs price
level_vs_pred <- ggplot(data = d) +
  geom_point(aes(y=ylev, x=predlev), color = "cyan4", size = 1,
             shape = 16, alpha = 0.6, show.legend=FALSE, na.rm=TRUE) +
  geom_segment(aes(x = 0, y = 0, xend = 350, yend =350), size=0.8, color="deeppink4", linetype=2) +
  labs(y = "Price (US dollars)", x = "Predicted price  (US dollars)") +
  theme_classic() 
level_vs_pred

save_fig("Fig13-level-vs-pred", output, "small")

```





